In [13]:
# !pip install torch

In [2]:
import torch
import numpy as np
from torch import nn 
from torch import optim
from torch.autograd import Variable

### 1. Создайте случайный FloatTensor размера 3x4x5

In [3]:
a = torch.rand(3, 4, 5)
print(a)

tensor([[[0.8151, 0.0883, 0.9598, 0.1683, 0.0057],
         [0.0274, 0.3708, 0.0053, 0.1274, 0.6964],
         [0.7701, 0.6428, 0.9882, 0.8370, 0.2867],
         [0.2583, 0.8428, 0.5036, 0.5987, 0.0813]],

        [[0.9695, 0.8700, 0.5847, 0.3763, 0.0278],
         [0.1129, 0.8766, 0.0744, 0.5483, 0.8536],
         [0.6704, 0.2531, 0.6006, 0.1597, 0.4755],
         [0.9792, 0.7058, 0.0780, 0.5466, 0.1098]],

        [[0.5312, 0.8138, 0.4628, 0.3121, 0.5414],
         [0.5110, 0.5741, 0.5086, 0.2900, 0.5583],
         [0.1084, 0.8334, 0.7223, 0.3371, 0.2065],
         [0.5398, 0.5572, 0.4821, 0.8209, 0.0140]]])


### 2. Выведите его форму (shape)

In [4]:
print(a.shape)

torch.Size([3, 4, 5])


### 3. Приведите его к форме 6 X 10

In [6]:
b = a.reshape(6, 10)
print(b.shape)

torch.Size([6, 10])


### 4. Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [7]:
a_new = a * torch.tensor([1, 4, 2, 2, 1])
print(a_new)

tensor([[[0.8151, 0.3532, 1.9196, 0.3367, 0.0057],
         [0.0274, 1.4834, 0.0105, 0.2547, 0.6964],
         [0.7701, 2.5714, 1.9763, 1.6741, 0.2867],
         [0.2583, 3.3714, 1.0073, 1.1974, 0.0813]],

        [[0.9695, 3.4801, 1.1694, 0.7526, 0.0278],
         [0.1129, 3.5063, 0.1489, 1.0967, 0.8536],
         [0.6704, 1.0123, 1.2011, 0.3194, 0.4755],
         [0.9792, 2.8233, 0.1560, 1.0931, 0.1098]],

        [[0.5312, 3.2551, 0.9255, 0.6241, 0.5414],
         [0.5110, 2.2964, 1.0172, 0.5800, 0.5583],
         [0.1084, 3.3335, 1.4446, 0.6741, 0.2065],
         [0.5398, 2.2286, 0.9642, 1.6419, 0.0140]]])


### 5. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [8]:
b_new = b[:, :6] * (b[:, :6])
print(b_new)
print(b_new.shape)

tensor([[6.6432e-01, 7.7965e-03, 9.2121e-01, 2.8333e-02, 3.2722e-05, 7.4875e-04],
        [5.9307e-01, 4.1325e-01, 9.7646e-01, 7.0065e-01, 8.2196e-02, 6.6718e-02],
        [9.3995e-01, 7.5696e-01, 3.4189e-01, 1.4158e-01, 7.7425e-04, 1.2751e-02],
        [4.4938e-01, 6.4043e-02, 3.6066e-01, 2.5501e-02, 2.2610e-01, 9.5886e-01],
        [2.8222e-01, 6.6222e-01, 2.1416e-01, 9.7381e-02, 2.9313e-01, 2.6116e-01],
        [1.1761e-02, 6.9452e-01, 5.2174e-01, 1.1360e-01, 4.2648e-02, 2.9141e-01]])
torch.Size([6, 6])


### 6. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [9]:
v = torch.tensor([1, 0.5, 2], requires_grad=True)
print(v.grad)
z = v ** 3 + v - 75 * v
print(z)
z.backward(v)
print(v.grad)

None
tensor([ -73.0000,  -36.8750, -140.0000], grad_fn=<SubBackward0>)
tensor([ -71.0000,  -36.6250, -124.0000])


### 7. Создайте единичный тензор размера 5x6

In [10]:
t_one = torch.ones(5,6)
print(t_one)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


### 8. Переведите его в формат numpy

In [11]:
t_np = t_one.numpy()
print(t_np)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


### 9. Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5

In [12]:
w1 = Variable(torch.Tensor([2,2]), requires_grad = True)
x = Variable(torch.Tensor([2,2]), requires_grad = False)
y = Variable(torch.Tensor([2,2]), requires_grad = False)

optimizer = torch.optim.SGD([w1], lr=0.0001)

criterion = torch.nn.MSELoss()

pred = x**w1 - 2 * x**2 + 5

optimizer.zero_grad()
loss = criterion(pred, y)
loss.backward()
optimizer.step()  
print(f'loss:\t {loss.item()}\n')
print(f'w1:\t {w1.data}')

loss:	 1.0

w1:	 tensor([2.0003, 2.0003])
